### ISSUE TITLE
packagecontrol.io's version of this is old

### ISSUE THREAD

**Issue by WeeKnightGames** [ziglang/sublime-zig-language#11]
As near as I can tell, the version of sublime-zig-language that can be installed via Package Control is old. I am getting highlighting inside of words like `enumeration` (where `enum` gets highlighted)---which does not appear to be how the current regexes are written.

**Comment by dsego** [comment]
As a workaround, Sublime Text package control supports installing packages directly from a github repo:
```
Package Control: Add Repository   
 -> https://github.com/ziglang/sublime-zig-language
Package Control: Install Package     
 -> sublime-zig-language
```

**Comment by emekoi** [comment]
to solve this per the docs @andrewrk you'll need to make a new tag or release.

**Comment by andrewrk** [comment]
Thanks @emekoi. Are you interested in becoming a maintainer of this repo?

**Comment by emekoi** [comment]
sure, i'd love to.

**Comment by andrewrk** [comment]
Invite sent!
