### ISSUE TITLE
Package Control has old version of the repository

### ISSUE THREAD

**Issue by Tetralux** [ziglang/sublime-zig-language#23]
Package Control has v1.0.0 of this repo.
This doesn't include `try`, `await`, `async`, or toggling of comments.
Maybe other things. Update?

**Comment by emekoi** [comment]
according to [packagecontrol.io](https://packagecontrol.io/packages/Zig%20Language), the most recent version they have is 1.1.0. are you sure your installed packages are up to date?

**Comment by Tetralux** [comment]
At the time of writing the OP I had only _just_ installed from Package Control.
This does appear to fixed resolved now, however.
