### ISSUE TITLE
weird syntax coloring on github

### ISSUE THREAD

**Issue by andrewrk** [ziglang/sublime-zig-language#27]
https://github.com/ziglang/zig/issues/3129#issue-485968855

any idea what's going on here? it looks like too much stuff is red.
![Screenshot_2019-08-27_16-54-26](https://user-images.githubusercontent.com/106511/63807725-4bbc9d00-c8ec-11e9-8cf6-27df73a20b4b.png)

**Comment by daurnimator** [comment]
@giann recently had a similar issue in sublime.

**Comment by giann** [comment]
Yes I have the exact same issue on some files.

**Comment by emekoi** [comment]
can you send me links/copies of these files?

**Comment by giann** [comment]
Actually it seems ⌘+/ (comment selection) doesn't work with the new syntax?

**Comment by emekoi** [comment]
the analogue for windows being<kbd>ctrl</kbd>+<kbd>/</kbd>? this seems to work fine on the machines i have tested it on.

**Comment by andrewrk** [comment]
I'm not sure if the changes have rolled out on github yet, but here's another example:

https://github.com/ziglang/zig/blob/f7f3dedb1de405e0123c93a4a9e54503e02942ee/lib/std/io.zig#L1025

![Screenshot_2019-10-15_15-03-39](https://user-images.githubusercontent.com/106511/66861410-fbad9e80-ef5c-11e9-9f64-782a9113d77f.png)

**Comment by emekoi** [comment]
no, the last update was [August 29](https://github.com/github/linguist/releases/tag/v7.6.1). here's what that would look like now: ![zig_snip](https://user-images.githubusercontent.com/9454576/66862133-ec772280-ef55-11e9-8ba1-1cd1cfc9db6f.PNG)

**Comment by andrewrk** [comment]
> because types are first class values (at compile time) there are going to be some issues regarding type highlighting, because it's not possible to distinguish between a type and and regular identifiers.

Makes sense. If you wanted to do such coloring, it might make sense to do it based on whether the first letter is capitalized or not, but also having types and regular identifiers be the same color is perfectly reasonable. Especially when you consider that it's possible for the same variable to be a type or not-a-type, for example when doing an inline for loop over var args.
