### ISSUE TITLE
[Sublime Text] Struct field initializers aren't colored properly

### ISSUE THREAD

**Issue by darithorn** [ziglang/sublime-zig-language#35]
The last character of fields in struct initializers aren't colored properly. I'm not sure where this broke but I imagine something in the commit for TextMate compatibility broke it, since this worked properly the other day.

![Screenshot from 2020-04-15 18-57-19](https://user-images.githubusercontent.com/2891114/79406141-1cc26c80-7f4b-11ea-8e31-2604e3de907d.png)

**Comment by emekoi** [comment]
i think this broke in b25f8773e6a75c8b1b2bf9deddbe13a153ca85a1 to fix #31

**Comment by darithorn** [comment]
Now they're not getting colored at all. Is that the intended behavior?

**Comment by emekoi** [comment]
that's the status quo behavior. they were being highlighted because they were being detected as enum literals.
