### ISSUE TITLE
syblime-syntax

### ISSUE THREAD

**Issue by haze** [ziglang/sublime-zig-language#41]
I am unable to convert the `.tmLanguage` files to `.sublime-syntax` with my latest build of sublime text. Is anyone else able to do the conversion so I can use the highlighter with things like Zola?

**Comment by haze** [comment]
I was unable to find a tool / solution for converting that file, sorry.

**Comment by emekoi** [comment]
no problem. thanks for looking!

**Comment by gwenzek** [comment]
@emekoi Would you be interested if I added a few enhacement to the .sublime-syntax ?

Things I'd want to do:
[ ] Remove the look behind, to use the new engine (faster)
[ ] Add the tests to the symbol list
[ ] Add types aliases `const WordCount = std.HashMap([]const u8, i32)`
[ ] Add tests (for the syntax) based on sample.zig
[ ] Remove improper use of `entity.name` (see [guidelines](https://www.sublimetext.com/docs/3/scope_naming.html))
[ ] More precise scopes for parenthesis, braces and brackets
[ ] More precise scopes for try/catch/for/while/, ....
[ ] support of `=>` operator

For context I'm the original author of the [C# syntax](https://github.com/sublimehq/Packages/blob/master/C%23/C%23.sublime-syntax) (it has been improved a lot over the years by others).

This will make the syntax diverge from the VS Code one, but I think it will be for the best.

**Comment by emekoi** [comment]
@gwenzek sure go ahead! on a side note, would it be possible to backport any of those changes to the `.*-tmLanguage` syntax files?

**Comment by gwenzek** [comment]
> would it be possible to backport any of those changes to the .*-tmLanguage syntax files?

I guess for the simple one like adding operators it will be doable, 
but for the rest I'm not sure what's the point.
A syntax is only useful in the context of an ecosystem. The scopes name must match the scopes used by theme creators.
Sublime Text do have guidelines about those, but they have some differences with other editor ecosystems.

**Comment by emekoi** [comment]
solved by #45.

**Comment by emekoi** [comment]
solved by #45.
