### ISSUE TITLE
zig.executable setting is unused

### ISSUE THREAD

**Issue by squeek502** [ziglang/sublime-zig-language#42]
https://github.com/ziglang/sublime-zig-language/blob/65b42cc8630d8aa803354a9693798cdfd7c88a79/Settings/Zig.sublime-settings#L2-L3

Doesn't seem to actually be used anywhere or affect anything.

**Comment by daurnimator** [comment]
AFAIK its used to e.g. run `zig fmt` on save?

**Comment by squeek502** [comment]
That's the intention but it's not actually used.

**Comment by aequitas** [comment]
TextMate uses it's own build scripts in https://github.com/ziglang/sublime-zig-language/tree/master/Commands. So it would be no problem I guess.

**Comment by haferburg** [comment]
Is there any workaround other than putting the zig executable in the PATH?

**Comment by knadh** [comment]
@haferburg https://robdodson.me/posts/hacking-the-path-variable-in-sublime-text/

This hack can be used to add whatever path to Sublime's internal PATH variable.
