### ISSUE TITLE
Snippets not working?

### ISSUE THREAD

**Issue by 01271** [ziglang/sublime-zig-language#50]
Installed the package using package manager, snippets don't seem to work.
If I type in main and then press tab or enter I'd expect it to fill in the rest. What gives?

**Comment by gwenzek** [comment]
I can't reproduce in ST 4099.

What ST version are you using ?
What is the syntax of the file ? Can you check that there is "Zig" written in the bottom right corner of the size ?
Normally all `.zig` files should be open with the Zig syntax and snippets.
But if you installed the package, with the file opened ST won't change the syntax when installing the plugin.

Try reopening the file, and restarting ST if that's not enough.

**Comment by emekoi** [comment]
i also cannot reproduce in Sublime Text Build 4113.

**Comment by kevinsjoberg** [comment]
I can confirm this. I just installed Sublime Text, build 4113, and while installing the Zig package the following error appear:

<img width="372" alt="Screenshot 2021-07-23 at 12 35 44" src="https://user-images.githubusercontent.com/503025/126770627-a8d29d86-2ef7-4932-9691-5885a31466d6.png">

Opening a new document, Setting `Set Syntax: Zig` and then writing `main` followed by a tab, does nothing. A restart didn't help.

**Comment by emekoi** [comment]
sorry, i think i know what the issue is. snippets were added June 3rd, but the last release was April 18th. i'll try to merge #54 and #43 and push a (long overdue) release tommorow.

**Comment by emekoi** [comment]
please let me know if snippets are still not working when the package control picks up the new version.

**Comment by kevinsjoberg** [comment]
I've released a new version, [1.5.0](https://github.com/ziglang/sublime-zig-language/releases/tag/1.5.0), that is [semver](https://semver.org) compatible. It's now available in Package Control. Enjoy!
