### ISSUE TITLE
1.5 not showing up in Package Control

### ISSUE THREAD

**Issue by squeek502** [ziglang/sublime-zig-language#56]
https://packagecontrol.io/packages/Zig%20Language still has 1.4.5.

Any idea why that would be?

**Comment by emekoi** [comment]
i don't know for some reason package control has not detected that a new tag has been published. i can try publishing a new tag and see if that's picked up?

**Comment by squeek502** [comment]
Maybe it's tripping up on the `1.5` to `1.4.5` comparison? Maybe it needs to be `1.5.0`?

**Comment by sigod** [comment]
> Maybe it needs to be 1.5.0?

I think so. According to the SemVer specs:
> 2. A normal version number MUST take the form X.Y.Z ...

**Comment by kevinsjoberg** [comment]
@emekoi could you try to do a new release where the tag is compatible with [semver](https://semver.org)? From the [docs](https://packagecontrol.io/docs/submitting_a_package#Step_4):

> If you are using GitHub or BitBucket for your hosting, you will need to create a tag each time you want to make a new version available to users. The tag names must be a semantic version number.

**Comment by kevinsjoberg** [comment]
I've dropped the offending tag, `1.5`, and done a new release under `1.5.0`. I'm happy to say that the new version is now available in Package Control. See https://packagecontrol.io/packages/Zig%20Language. 🎉
