### ISSUE TITLE
Installing through package control does not work 

### ISSUE THREAD

**Issue by hgranthorner** [ziglang/sublime-zig-language#58]
I've tried uninstalling and installing the zig package, and restarting sublime, and I continue to get this issue.
Error message:
```
error: error loading meta info from Packages/Zig Language/Preferences/Comments.tmPreferences: Error parsing plist xml: expected < in file Packages/Zig Language/Preferences/Comments.tmPreferences on line: 1
```

**Comment by kevinsjoberg** [comment]
I've released a new version, [1.5.0](https://github.com/ziglang/sublime-zig-language/releases/tag/1.5.0), that is [semver](https://semver.org) compatible. It's now available in Package Control and it resolves this issue.

Enjoy!
